// Package ids converts between the UUIDv7 stored in Postgres and the external
// form used by the API: a three-letter resource prefix followed by the same
// 128 bits in Crockford base32.
//
// See ARCHITECTURE.md §4.31.
package ids

import (
	"errors"
	"strings"

	"github.com/google/uuid"
)

// Prefix identifies the resource an external identifier belongs to. Pasting a
// delivery id where an endpoint id is expected becomes a named validation
// error instead of a puzzling 404.
type Prefix string

const (
	Organization    Prefix = "org"
	Application     Prefix = "app"
	Endpoint        Prefix = "ept"
	Event           Prefix = "evt"
	Delivery        Prefix = "dlv"
	DeliveryAttempt Prefix = "att"
)

var (
	// ErrMalformed means the base32 body is not a valid 128-bit identifier.
	ErrMalformed = errors.New("ids: malformed identifier")
	// ErrWrongPrefix means the identifier belongs to another resource.
	ErrWrongPrefix = errors.New("ids: wrong resource prefix")
)

const (
	alphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
	encoded  = 26 // 128 bits in 5-bit groups, rounded up
)

// New returns a fresh UUIDv7. Identifiers are generated by the application and
// never by the database: the ingress needs the delivery id before the insert,
// because that id is what goes on the queue.
func New() (uuid.UUID, error) {
	return uuid.NewV7()
}

// Render returns the base32 body with no prefix. Correlation ids use this:
// they are not resources, so they carry no prefix.
func Render(id uuid.UUID) string {
	v := [16]byte(id)
	out := make([]byte, encoded)
	for i := encoded - 1; i >= 0; i-- {
		out[i] = alphabet[v[15]&0x1f]
		shiftRight5(&v)
	}
	return string(out)
}

// Encode returns the external form of id for resource p.
func Encode(p Prefix, id uuid.UUID) string {
	return string(p) + "_" + Render(id)
}

// Parse decodes an external identifier, requiring it to carry prefix p.
// Input is case-insensitive and tolerates the ambiguous Crockford letters:
// I and L read as 1, O reads as 0.
func Parse(p Prefix, s string) (uuid.UUID, error) {
	want := string(p) + "_"
	if !strings.HasPrefix(s, want) {
		return uuid.Nil, ErrWrongPrefix
	}
	body := s[len(want):]
	if len(body) != encoded {
		return uuid.Nil, ErrMalformed
	}

	var v [16]byte
	for i := 0; i < encoded; i++ {
		d, ok := decodeChar(body[i])
		if !ok {
			return uuid.Nil, ErrMalformed
		}
		if overflow := shiftLeft5(&v, d); overflow {
			return uuid.Nil, ErrMalformed
		}
	}
	return uuid.UUID(v), nil
}

// shiftRight5 divides the big-endian 128-bit value by 32.
func shiftRight5(v *[16]byte) {
	var carry byte
	for i := 0; i < 16; i++ {
		cur := v[i]
		v[i] = cur>>5 | carry<<3
		carry = cur & 0x1f
	}
}

// shiftLeft5 multiplies the big-endian 128-bit value by 32 and adds add.
// It reports whether the result would exceed 128 bits.
func shiftLeft5(v *[16]byte, add byte) bool {
	if v[0]>>3 != 0 {
		return true
	}
	for i := 0; i < 15; i++ {
		v[i] = v[i]<<5 | v[i+1]>>3
	}
	v[15] = v[15]<<5 | add
	return false
}

func decodeChar(c byte) (byte, bool) {
	switch {
	case c >= 'a' && c <= 'z':
		c -= 'a' - 'A'
	}
	switch c {
	case 'I', 'L':
		return 1, true
	case 'O':
		return 0, true
	}
	if i := strings.IndexByte(alphabet, c); i >= 0 {
		return byte(i), true
	}
	return 0, false
}
