package main

import (
	"encoding/base64"
	"errors"
	"slices"
	"strings"
	"testing"

	"github.com/victorzix/vhook/internal/errs"
)

const (
	testDatabaseURL = "postgres://u:p@localhost:5432/vhook"
	testRabbitURL   = "amqp://guest:guest@localhost:5672/"
	testAdminEnv    = "token-administrativo-de-teste"
)

func validMasterKey() string {
	return base64.StdEncoding.EncodeToString([]byte("0123456789abcdef0123456789abcdef"))
}

// setValidEnv fills every required variable, so each test only has to break
// the one it is about.
func setValidEnv(t *testing.T) {
	t.Helper()
	t.Setenv("DATABASE_URL", testDatabaseURL)
	t.Setenv("RABBITMQ_URL", testRabbitURL)
	t.Setenv("VHOOK_ADMIN_TOKEN", testAdminEnv)
	t.Setenv("VHOOK_MASTER_KEY", validMasterKey())
	t.Setenv("VHOOK_SSRF_ALLOWLIST", "")
}

func TestLoadConfigReadsTheThreeVariables(t *testing.T) {
	setValidEnv(t)
	t.Setenv("VHOOK_HTTP_ADDR", ":9090")

	cfg, err := loadConfig()
	if err != nil {
		t.Fatalf("loadConfig() error = %v", err)
	}
	if cfg.httpAddr != ":9090" {
		t.Errorf("httpAddr = %q, want :9090", cfg.httpAddr)
	}
	if cfg.databaseURL != testDatabaseURL {
		t.Errorf("databaseURL = %q", cfg.databaseURL)
	}
	if cfg.rabbitURL != testRabbitURL {
		t.Errorf("rabbitURL = %q", cfg.rabbitURL)
	}
}

func TestLoadConfigDefaultsTheHTTPAddress(t *testing.T) {
	setValidEnv(t)
	t.Setenv("VHOOK_HTTP_ADDR", "")

	cfg, err := loadConfig()
	if err != nil {
		t.Fatalf("loadConfig() error = %v", err)
	}
	if cfg.httpAddr != ":8080" {
		t.Errorf("httpAddr = %q, want :8080", cfg.httpAddr)
	}
}

func TestLoadConfigReadsTheManagementSecrets(t *testing.T) {
	setValidEnv(t)

	cfg, err := loadConfig()
	if err != nil {
		t.Fatalf("loadConfig() error = %v", err)
	}
	if cfg.adminToken != testAdminEnv {
		t.Errorf("adminToken = %q", cfg.adminToken)
	}
	// The api decodes the same base64 the adminctl prints: one variable, one
	// encoding, or a key generated by one tool would not open what the other
	// sealed.
	if len(cfg.masterKey) != 32 {
		t.Errorf("masterKey tem %d bytes, queria 32", len(cfg.masterKey))
	}
}

func TestLoadConfigFailsWhenASecretIsMissing(t *testing.T) {
	tests := []struct{ name, unset string }{
		{"sem banco", "DATABASE_URL"},
		{"sem fila", "RABBITMQ_URL"},
		// Sem estes dois o processo não pode subir: um sem token administrativo
		// serviria o management a qualquer um, e um sem chave mestra gravaria
		// secret que ninguém consegue ler de volta.
		{"sem token administrativo", "VHOOK_ADMIN_TOKEN"},
		{"sem chave mestra", "VHOOK_MASTER_KEY"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			setValidEnv(t)
			t.Setenv(tt.unset, "")

			_, err := loadConfig()
			if !errors.Is(err, errs.MissingConfig) {
				t.Fatalf("error = %v, queria errs.MissingConfig", err)
			}
			// A mensagem precisa nomear a variável: sem isso o operador
			// descobre qual falta por tentativa e erro.
			if !contains(err.Error(), tt.unset) {
				t.Errorf("error = %v, devia nomear %s", err, tt.unset)
			}
		})
	}
}

func TestLoadConfigRejectsAMalformedMasterKey(t *testing.T) {
	for _, tt := range []struct{ name, value string }{
		{"não é base64", "!!!nao-e-base64!!!"},
		{"curta", base64.StdEncoding.EncodeToString([]byte("curta"))},
	} {
		t.Run(tt.name, func(t *testing.T) {
			setValidEnv(t)
			t.Setenv("VHOOK_MASTER_KEY", tt.value)

			_, err := loadConfig()
			if !errors.Is(err, errs.MissingConfig) {
				t.Fatalf("error = %v, queria errs.MissingConfig", err)
			}
			if !contains(err.Error(), "VHOOK_MASTER_KEY") {
				t.Errorf("error = %v, devia nomear VHOOK_MASTER_KEY", err)
			}
		})
	}
}

// Nomear a variável é obrigatório; citar o valor é proibido. Os dois segredos
// desta configuração nunca podem chegar a um terminal, a um log ou a um
// transcript de CI.
func TestLoadConfigNeverQuotesASecretValue(t *testing.T) {
	for _, tt := range []struct{ name, unset, secret string }{
		{"chave mestra inválida", "", validMasterKey()},
		{"token ausente", "VHOOK_ADMIN_TOKEN", testAdminEnv},
	} {
		t.Run(tt.name, func(t *testing.T) {
			setValidEnv(t)
			t.Setenv("VHOOK_MASTER_KEY", base64.StdEncoding.EncodeToString([]byte("curta")))
			if tt.unset != "" {
				t.Setenv(tt.unset, "")
			}

			_, err := loadConfig()
			if err == nil {
				t.Fatal("loadConfig() devia falhar")
			}
			if contains(err.Error(), tt.secret) {
				t.Errorf("o valor do segredo vazou na mensagem: %v", err)
			}
		})
	}
}

func TestLoadConfigSplitsTheSSRFAllowlist(t *testing.T) {
	tests := []struct {
		name  string
		value string
		want  []string
	}{
		{"vazia", "", nil},
		{"um host", "sink", []string{"sink"}},
		{"vários", "sink,outro", []string{"sink", "outro"}},
		// Espaço em volta da vírgula é erro de digitação comum num .env, e um
		// host com espaço nunca casaria com o host da URL.
		{"com espaços", " sink , outro ", []string{"sink", "outro"}},
		{"vírgula sobrando", "sink,,", []string{"sink"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			setValidEnv(t)
			t.Setenv("VHOOK_SSRF_ALLOWLIST", tt.value)

			cfg, err := loadConfig()
			if err != nil {
				t.Fatalf("loadConfig() error = %v", err)
			}
			if !slices.Equal(cfg.ssrfAllowlist, tt.want) {
				t.Errorf("ssrfAllowlist = %v, want %v", cfg.ssrfAllowlist, tt.want)
			}
		})
	}
}

func contains(haystack, needle string) bool {
	return len(haystack) >= len(needle) && strings.Contains(haystack, needle)
}
