// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
)

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadyStatus.
const (
	ReadyStatusReady ReadyStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadyStatus enum.
func (e ReadyStatus) Valid() bool {
	switch e {
	case ReadyStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for ReadyChecksPostgres.
const (
	ReadyChecksPostgresOk ReadyChecksPostgres = "ok"
)

// Valid indicates whether the value is a known member of the ReadyChecksPostgres enum.
func (e ReadyChecksPostgres) Valid() bool {
	switch e {
	case ReadyChecksPostgresOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadyChecksRabbitmq.
const (
	ReadyChecksRabbitmqOk ReadyChecksRabbitmq = "ok"
)

// Valid indicates whether the value is a known member of the ReadyChecksRabbitmq enum.
func (e ReadyChecksRabbitmq) Valid() bool {
	switch e {
	case ReadyChecksRabbitmqOk:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Error ErrorBody `json:"error"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code `MOD-TYP-NNN`. Contrato estável — pode ser usado em lógica de decisão.
	// Ver `docs/ERRORS.md` para a taxonomia.
	//
	//
	// Examples: AUT-CRD-001
	Code ErrorCode `json:"code"`

	// CorrelationId Liga esta resposta ao log estruturado. Obrigatório: como não
	// há mensagem, é a única forma de investigar um caso relatado.
	//
	//
	// Examples: 01HQZX3K7YB2N4M8P6R9T5V0W1
	CorrelationId string `json:"correlation_id"`

	// Details Falhas por campo, para o dashboard destacar o formulário sem
	// que o backend produza texto. Ausente quando não se aplica.
	Details *[]ErrorDetail `json:"details,omitempty"`
}

// ErrorCode `MOD-TYP-NNN`. Contrato estável — pode ser usado em lógica de decisão.
// Ver `docs/ERRORS.md` para a taxonomia.
//
// Examples: AUT-CRD-001
type ErrorCode = string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Code `MOD-TYP-NNN`. Contrato estável — pode ser usado em lógica de decisão.
	// Ver `docs/ERRORS.md` para a taxonomia.
	//
	//
	// Examples: AUT-CRD-001
	Code ErrorCode `json:"code"`

	// Field Campo do formulário, ou nome da sub-checagem quando o erro tem
	// partes — em `/readyz`, `postgres` ou `rabbitmq`.
	//
	//
	// Examples: url
	Field string `json:"field"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Ready defines model for Ready.
type Ready struct {
	// Checks Só aparece na resposta 200, e aí todas as dependências estão `ok`.
	// Falha é expressa pelo envelope de erro: o `code` é o da primeira
	// dependência a falhar na ordem de checagem, e `details` lista todas.
	//
	// Schema nomeado em vez de objeto embutido para que o nome do tipo
	// gerado seja previsível — objeto anônimo faz o gerador inventar o nome.
	Checks ReadyChecks `json:"checks"`
	Status ReadyStatus `json:"status"`
}

// ReadyStatus defines model for Ready.Status.
type ReadyStatus string

// ReadyChecks Só aparece na resposta 200, e aí todas as dependências estão `ok`.
// Falha é expressa pelo envelope de erro: o `code` é o da primeira
// dependência a falhar na ordem de checagem, e `details` lista todas.
//
// Schema nomeado em vez de objeto embutido para que o nome do tipo
// gerado seja previsível — objeto anônimo faz o gerador inventar o nome.
type ReadyChecks struct {
	Postgres ReadyChecksPostgres `json:"postgres"`
	Rabbitmq ReadyChecksRabbitmq `json:"rabbitmq"`
}

// ReadyChecksPostgres defines model for ReadyChecks.Postgres.
type ReadyChecksPostgres string

// ReadyChecksRabbitmq defines model for ReadyChecks.Rabbitmq.
type ReadyChecksRabbitmq string

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = Error

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Liveness
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetMetrics Métricas Prometheus
	// (GET /metrics)
	GetMetrics(w http.ResponseWriter, r *http.Request)
	// GetReadiness Readiness
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetHealth Liveness
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMetrics Métricas Prometheus
// (GET /metrics)
func (_ Unimplemented) GetMetrics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReadiness Readiness
// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/metrics", wrapper.GetMetrics)
	})

	return r
}
