// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT count(*) FROM organizations
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (id, organization_id, name, api_key_hash, locale, backoff_profile)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, name, api_key_hash, plan, backoff_profile, locale, created_at
`

type CreateApplicationParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	ApiKeyHash     string
	Locale         string
	BackoffProfile string
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.ApiKeyHash,
		arg.Locale,
		arg.BackoffProfile,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ApiKeyHash,
		&i.Plan,
		&i.BackoffProfile,
		&i.Locale,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at
`

type CreateOrganizationParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.ID, arg.Name)
	var i Organization
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const lockBootstrap = `-- name: LockBootstrap :exec
SELECT pg_advisory_xact_lock($1)
`

// Serialises concurrent bootstrap runs. Held until the transaction ends, so
// the second run blocks and then sees the organization the first one created.
// Nothing in the schema serialises them otherwise: each run mints a distinct
// api_key_hash, so the UNIQUE on that column never collides.
func (q *Queries) LockBootstrap(ctx context.Context, pgAdvisoryXactLock int64) error {
	_, err := q.db.Exec(ctx, lockBootstrap, pgAdvisoryXactLock)
	return err
}
