// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoints.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEndpoints = `-- name: CountEndpoints :one
SELECT count(*) FROM endpoints WHERE application_id = $1
`

func (q *Queries) CountEndpoints(ctx context.Context, applicationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEndpoints, applicationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (id, application_id, url, secret_encrypted)
VALUES ($1, $2, $3, $4)
RETURNING id, application_id, url, secret_encrypted, status, consecutive_failures, disabled_at, created_at, updated_at
`

type CreateEndpointParams struct {
	ID              pgtype.UUID
	ApplicationID   pgtype.UUID
	Url             string
	SecretEncrypted []byte
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.ID,
		arg.ApplicationID,
		arg.Url,
		arg.SecretEncrypted,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Url,
		&i.SecretEncrypted,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, application_id, url, secret_encrypted, status, consecutive_failures, disabled_at, created_at, updated_at FROM endpoints WHERE id = $1 AND application_id = $2
`

type GetEndpointParams struct {
	ID            pgtype.UUID
	ApplicationID pgtype.UUID
}

// O application_id no WHERE é o que faz recurso de outro tenant devolver 404
// em vez de 403: existência e autorização ficam indistinguíveis de fora.
func (q *Queries) GetEndpoint(ctx context.Context, arg GetEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpoint, arg.ID, arg.ApplicationID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Url,
		&i.SecretEncrypted,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, application_id, url, secret_encrypted, status, consecutive_failures, disabled_at, created_at, updated_at FROM endpoints
WHERE application_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListEndpoints(ctx context.Context, applicationID pgtype.UUID) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpoints, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Url,
			&i.SecretEncrypted,
			&i.Status,
			&i.ConsecutiveFailures,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockApplication = `-- name: LockApplication :one
SELECT id FROM applications WHERE id = $1 FOR UPDATE
`

// Trava a linha da application para o resto da transação. Tomada ANTES da
// contagem: sem ela, duas criações simultâneas leem o mesmo total e ambas
// inserem. É por tenant, então dois clientes não se esperam.
func (q *Queries) LockApplication(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockApplication, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const updateEndpointURL = `-- name: UpdateEndpointURL :one
UPDATE endpoints
SET url = $3, updated_at = now()
WHERE id = $1 AND application_id = $2
RETURNING id, application_id, url, secret_encrypted, status, consecutive_failures, disabled_at, created_at, updated_at
`

type UpdateEndpointURLParams struct {
	ID            pgtype.UUID
	ApplicationID pgtype.UUID
	Url           string
}

func (q *Queries) UpdateEndpointURL(ctx context.Context, arg UpdateEndpointURLParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpointURL, arg.ID, arg.ApplicationID, arg.Url)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Url,
		&i.SecretEncrypted,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
