// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	ApiKeyHash     string
	Plan           string
	BackoffProfile string
	Locale         string
	CreatedAt      pgtype.Timestamptz
}

type Delivery struct {
	ID            pgtype.UUID
	EventID       pgtype.UUID
	EndpointID    pgtype.UUID
	Status        string
	AttemptCount  int32
	NextAttemptAt pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type DeliveryAttempt struct {
	ID              pgtype.UUID
	DeliveryID      pgtype.UUID
	AttemptNumber   int32
	StatusCode      pgtype.Int4
	ResponseTimeMs  pgtype.Int4
	ResponseSnippet pgtype.Text
	Error           pgtype.Text
	AttemptedAt     pgtype.Timestamptz
}

type Endpoint struct {
	ID                  pgtype.UUID
	ApplicationID       pgtype.UUID
	Url                 string
	SecretEncrypted     []byte
	Status              string
	ConsecutiveFailures int32
	DisabledAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type Event struct {
	ID             pgtype.UUID
	ApplicationID  pgtype.UUID
	EventType      string
	Payload        pgtype.Text
	IdempotencyKey pgtype.Text
	ReceivedAt     pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}
